//go:build no_runtime_type_checking

package awseventbridgepipes

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetTypeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReference) validateSetValueParameters(val *string) error {
	return nil
}

func validateNewAwsPipesPipe_TargetParametersEcsTaskParametersOverridesContainerOverrideResourceRequirementPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

