//go:build no_runtime_type_checking

package awslexv2models

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateAllWithMapKeyParameters(mapKeyAttributeName *string) error {
	return nil
}

func (a *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateGetParameters(index *float64) error {
	return nil
}

func (a *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func (j *jsiiProxy_AwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyList) validateSetWrapsSetParameters(val *bool) error {
	return nil
}

func validateNewAwsLexv2ModelsIntent_ConfirmationSettingConfirmationConditionalConditionalBranchResponseMessageGroupVariationPlainTextMessagePropertyListParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, wrapsSet *bool) error {
	return nil
}

