//go:build no_runtime_type_checking

package awslexv2models

// Building without runtime type checking enabled, so all the below just return nil

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validatePutMessageParameters(value interface{}) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validatePutVariationParameters(value interface{}) error {
	return nil
}

func (t *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_TfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewTfIntent_FulfillmentCodeHookFulfillmentUpdatesSpecificationStartResponseMessageGroupPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

