//go:build no_runtime_type_checking

package awsarcregionswitch

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetClusterArnParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetCrossAccountRoleParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetExternalIdParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsArcregionswitchPlan_WorkflowStepParallelConfigStepEksResourceScalingConfigEksClustersPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

