//go:build no_runtime_type_checking

package awsarcregionswitch

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateSetMinimumSuccessPercentageParameters(val *float64) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsArcregionswitchPlan_WorkflowStepParallelConfigStepEcsCapacityIncreaseConfigUngracefulPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

