//go:build no_runtime_type_checking

package awsbatch

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetAllowPrivilegeEscalationParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetInternalValueParameters(val *AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextProperty) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetPrivilegedParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetReadOnlyRootFileSystemParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetRunAsGroupParameters(val *float64) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetRunAsNonRootParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetRunAsUserParameters(val *float64) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsBatchJobDefinition_EksPropertiesPodPropertiesInitContainersSecurityContextPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

