//go:build no_runtime_type_checking

package awskinesisfirehose

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validatePutParametersParameters(value interface{}) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReference) validateSetTypeParameters(val *string) error {
	return nil
}

func validateNewAwsKinesisFirehoseDeliveryStream_IcebergConfigurationProcessingConfigurationProcessorsPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

