//go:build no_runtime_type_checking

package awskinesisfirehose

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validatePutCloudwatchLoggingOptionsParameters(value *AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationCloudwatchLoggingOptionsProperty) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validatePutProcessingConfigurationParameters(value *AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationProcessingConfigurationProperty) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validatePutS3ConfigurationParameters(value *AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationS3ConfigurationProperty) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validatePutVpcConfigParameters(value *AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationVpcConfigProperty) error {
	return nil
}

func (a *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetBufferingIntervalParameters(val *float64) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetBufferingSizeParameters(val *float64) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetCollectionEndpointParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetIndexNameParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetInternalValueParameters(val *AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationProperty) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetRetryDurationParameters(val *float64) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetRoleArnParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetS3BackupModeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsKinesisFirehoseDeliveryStream_OpensearchserverlessConfigurationPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

