//go:build no_runtime_type_checking

package awssagemakerai

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateSetAcceptEulaParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateSetInternalValueParameters(val *AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigProperty) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsSagemakerModel_PrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfigPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

