//go:build no_runtime_type_checking

package awssagemakerai

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateAllWithMapKeyParameters(mapKeyAttributeName *string) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateGetParameters(index *float64) error {
	return nil
}

func (a *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func (j *jsiiProxy_AwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyList) validateSetWrapsSetParameters(val *bool) error {
	return nil
}

func validateNewAwsSagemakerHyperParameterTuningJob_TrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecificationsPropertyListParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, wrapsSet *bool) error {
	return nil
}

