//go:build no_runtime_type_checking

package bedrockagents

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetMetadataFieldParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetTextFieldParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReference) validateSetVectorFieldParameters(val *string) error {
	return nil
}

func validateNewAwsKnowledgeBase_StorageConfigurationRedisEnterpriseCloudConfigurationFieldMappingPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

