//go:build no_runtime_type_checking

package awsappmesh

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateSetCertificateAuthorityArnsParameters(val *[]*string) error {
	return nil
}

func (j *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateSetInternalValueParameters(val *AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmProperty) error {
	return nil
}

func (j *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsValidationTrustAcmPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

