//go:build no_runtime_type_checking

package awsappmesh

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateSetInternalValueParameters(val *DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFileProperty) error {
	return nil
}

func (j *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsAppmeshVirtualGateway_SpecBackendDefaultsClientPolicyTlsCertificateFilePropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

