//go:build no_runtime_type_checking

package awss3control

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validatePutEncryptionParameters(value *AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationEncryptionProperty) error {
	return nil
}

func (a *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetAccountIdParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetArnParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetFormatParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetInternalValueParameters(val *AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationProperty) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetOutputSchemaVersionParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetPrefixParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsS3ControlStorageLensConfiguration_StorageLensConfigurationExpandedPrefixesDataExportS3BucketDestinationPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

