//go:build no_runtime_type_checking

package awsbedrockagents

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetGuardrailIdentifierParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetGuardrailVersionParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsBedrockagentFlow_DefinitionNodeConfigurationKnowledgeBaseGuardrailConfigurationPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

