//go:build no_runtime_type_checking

package awsbedrockagents

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetAuthTypeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetCredentialsSecretArnParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetHostUrlParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetInternalValueParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsBedrockagentDataSource_DataSourceConfigurationSalesforceConfigurationSourceConfigurationPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

