//go:build no_runtime_type_checking

package awstransferfamily

// Building without runtime type checking enabled, so all the below just return nil

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (a *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetFileSystemIdParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetInternalValueParameters(val *AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationProperty) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetPathParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_AwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewAwsTransferWorkflow_StepsCopyStepDetailsDestinationFileLocationEfsFileLocationPropertyOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

